### ISSUE TITLE
output stream error

### ISSUE THREAD

**Issue by syarul** [juliangruber/browser-run#159]
Having issue with tape-run v6 upwards which base on browser-run 6.

```
> webpack --config webpack.test.js

TAP version 13
# test success
ok 1 should be equal
Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'webpack://webpack-tape-run/./node_modules/tape/lib/test.js?'.
    at Array.<anonymous> (http://localhost:54901/reporter.js:6627:9)
    at http://localhost:54901/reporter.js:6604:24
    at retrieveSourceMapURL (http://localhost:54901/reporter.js:6675:14)
    at Array.<anonymous> (http://localhost:54901/reporter.js:6692:26)
    at http://localhost:54901/reporter.js:6604:24
    at mapSourcePosition (http://localhost:54901/reporter.js:6722:21)
    at wrapCallSite (http://localhost:54901/reporter.js:6894:20)
    at http://localhost:54901/reporter.js:6929:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (http://localhost:54901/reporter.js:6928:24)
# C:\Users\hotti\distro\webpack-tape-run\test.js: line 7, column 3-9

    t.end()
    ^^^^^^^

# coverage: 13/14 (92.85 %)

asset test.js 296 KiB [compared for emit] (name: main)
runtime modules 221 bytes 1 module
modules by path ./node_modules/ 241 KiB 48 modules
./test.js 1.39 KiB [built] [code generated]
fs (ignored) 15 bytes [built] [code generated]
./util.inspect (ignored) 15 bytes [built] [code generated]
buffer (ignored) 15 bytes [built] [code generated]
util (ignored) 15 bytes [built] [code generated]
buffer (ignored) 15 bytes [built] [code generated]
util (ignored) 15 bytes [built] [code generated]
buffer (ignored) 15 bytes [built] [code generated]

ERROR in tests failed

ERROR in test reporter non-zero exit code

webpack 5.50.0 compiled with 2 errors in 2431 ms
npm ERR! Test failed.  See above for more details.
```

**Comment by juliangruber** [comment]
Can you share more about your setup? Did you follow this tutorial https://github.com/juliangruber/tape-run#with-webpack?

**Comment by juliangruber** [comment]
Could you share your test file too?

**Comment by syarul** [comment]
You can clone [https://github.com/syarul/webpack-tape-run/tree/tape-run-v9](https://github.com/syarul/webpack-tape-run/tree/tape-run-v9)
```
npm install
npm test
```
I put extra logging to the code, the issue might be related to electron-stream, since this [commit](https://github.com/juliangruber/browser-run/commit/7fee43c8bbe499f28d6bd64719710b23f058fe73) is the starting failing, only occurs on failing test, but on success does not happen.
```
> webpack --config webpack.test.js

TAP version 13
# test success
ok 1 should be equal
Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'webpack://webpack-tape-run/./node_modules/tape/lib/test.js?'.
    at Array.<anonymous> (http://localhost:49685/reporter.js:6627:9)
    at http://localhost:49685/reporter.js:6604:24
    at retrieveSourceMapURL (http://localhost:49685/reporter.js:6675:14)
    at Array.<anonymous> (http://localhost:49685/reporter.js:6692:26)
    at http://localhost:49685/reporter.js:6604:24
    at mapSourcePosition (http://localhost:49685/reporter.js:6722:21)
    at wrapCallSite (http://localhost:49685/reporter.js:6894:20)
    at http://localhost:49685/reporter.js:6929:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (http://localhost:49685/reporter.js:6928:24)
{
  ok: false,
  asserts: [ { ok: true, number: 1, name: 'should be equal' } ],
  pass: [ { ok: true, number: 1, name: 'should be equal' } ],
  fail: [],
  todo: [],
  errors: [ { message: 'no plan found', line: 28 } ]
}
# C:\Users\hotti\distro\webpack-tape-run\test.js: line 7, column 3-9

    t.end()
    ^^^^^^^

# coverage: 13/14 (92.85 %)

asset test.js 296 KiB [compared for emit] (name: main)
runtime modules 221 bytes 1 module
modules by path ./node_modules/ 241 KiB 48 modules
./test.js 1.39 KiB [built] [code generated]
fs (ignored) 15 bytes [built] [code generated]
./util.inspect (ignored) 15 bytes [built] [code generated]
buffer (ignored) 15 bytes [built] [code generated]
util (ignored) 15 bytes [built] [code generated]
buffer (ignored) 15 bytes [built] [code generated]
util (ignored) 15 bytes [built] [code generated]
buffer (ignored) 15 bytes [built] [code generated]

ERROR in tests failed

ERROR in test reporter non-zero exit code

webpack 5.50.0 compiled with 2 errors in 2303 ms
npm ERR! Test failed.  See above for more details.
```

**Comment by syarul** [comment]
IMO, I think this similar to node.js on how to handle ```uncaughtException```. Where you need to feed the error back the tape-run, so that test will continue on failing
```js
process.on('uncaughtException', (err, origin) => {
  \\
});
