### ISSUE TITLE
Fail while running with default electron browser

### ISSUE THREAD

**Issue by ActiveObject** [juliangruber/browser-run#65]
I'm using next command:
```
echo "console.log('Hey from ' + location); window.close()" | browser-run
```

The Electron starts but with an error:

A JavaScript error occurred in the main process.
Uncaught Exception:
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/activeobject/.nvm/versions/node/v5.1.1/lib/node_modules/browser-run/node_modules/electron-stream/lib/runner.js:1:90)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

It seems that electron-stream module has been published with raw sources.
I'm using electron-stream@2.3.0.

**Comment by juliangruber** [comment]
i can't produce with latest browser-run. Can you try this:

```bash
$ git clone https://github.com/juliangruber/browser-run.git
$ cd browser-run
$ npm install
$ echo "console.log('Hey from ' + location); window.close()" | ./bin/bin.js
```

**Comment by ActiveObject** [comment]
It works now, don't know what was the problem. Thanks!
